version: "3"
services:
  master:
#    build: .
    image: 127.0.0.1:5000/myspark
    command: sh /opt/spark/sbin/start-master.sh
    hostname: spark-master
    ports:
      - 8080:8080
      - 8081:8081
      - 7077:7077
      - 4040:4040
  worker:
 #   build: .
    image: 127.0.0.1:5000/myspark
    deploy:
  #    mode: replicaetd
      replicas: 3
    command: sh /opt/spark/sbin/start-slave.sh spark://spark-master:7077
    hostname: spark-worker
    links:
      - master 
    ports:
      - 9080:8080
      - 9081:8081
      - 9077:7077
      - 9040:4040
